---

language: python
python:
  - 2.7

sudo: required
dist: trusty

cache:
  - pip

services:
  - docker

before_install:
  # Ansible doesn't play well with virtualenv
  - deactivate

install:
  - pip install --user ansible
  - git clone https://github.com/sstephenson/bats.git ../bats
  - pushd ../bats && ./install.sh ~/bats-install && popd
  - mkdir ~/bin
  - ln -s ~/bats-install/bin/bats ~/bin/bats

script:
  - bats tests/
